apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rgi6nozrq-go
  janus-idp.io/tekton: rgi6nozrq-go
  backstage.io/kubernetes-id: rgi6nozrq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rgi6nozrq-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
